---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:10.13
        name: postgres
        env:
        - name: POSTGRES_USER
          value: testuser
        - name: POSTGRES_DB
          value: testdatabase
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata     
        - name: POSTGRES_PASSWORD
          value: password
          #valueFrom:
            #secretKeyRef:
              #name: db-password
              #key: postgres-password
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres
      nodeSelector:
        database: "true"
      volumes:
      - name: postgres
        persistentVolumeClaim:
          claimName: postgres

