---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redmine
    spec:
      hostname: redmine
      containers:
      - image: redmine:4.1
        name: redmine
        env:
        - name: REDMINE_DB_POSTGRES
          value: db-service # указать сервис пода базы данных так как service это l4 балансировщик
        - name: REDMINE_DB_USERNAME
          value: redmine
        - name: REDMINE_DB_PASSWORD 
          value: password  
        - name: REDMINE_DB_DATABASE 
          value: redmine
        ports:
        - containerPort: 3000     
